apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:cams-data/clickhouse-deployment.git
    targetRevision: main
    path: ./apps
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true